import matplotlib.pyplot as plt
import networkx as nx

G.add_edge('Uthai thani','Nakorn sawan'weight=43)
G.add_edge('Nakorn sawan','Kampangpetch'weight=132)
G.add_edge('Nakorn sawan','Pijit'weight=104)
G.add_edge('Nakorn sawan','Petchchaboon'weight=174)
G.add_edge('Kampangpetch','Pijit'weight=100)
G.add_edge('Pijit','Kampangpetch'weight=133)
G.add_edge('Petchchaboon','Pitsanulok'weight=177)
G.add_edge('Pijit','Kampangpetch'weight=57)
G.add_edge('Kampangpetch','Pitsanulok'weight=110)
G.add_edge('Kampangpetch','Sukothai'weight=71)
G.add_edge('Kampangpetch','Tak'weight=62)
G.add_edge('Tak','Sukothai'weight=85)
G.add_edge('Sukothai','Pitsanulok'weight=58)
G.add_edge('Pitsanulok','Uttaradit'weight=108)
G.add_edge('Sukothai','Uttaradit'weight=91)
G.add_edge('Sukothai','Pair'weight=163)
G.add_edge('Sukothai','Lampang'weight=195)
G.add_edge('Tak','Lampang'weight=188)
G.add_edge('Tak','Lampoon'weight=241)
G.add_edge('Tak','Maehongsorn'weight=508)
G.add_edge('Pair','Uttaradit'weight=72)
G.add_edge('Lampang','Pair'weight=96)
G.add_edge('Lampang','Lampoon'weight=71)
G.add_edge('Chiangmai','Lampang'weight=114)
G.add_edge('Chiangmai','Lampoon'weight=21)
G.add_edge('Maehongsorn','Chiangmai'weight=237)
G.add_edge('Pair','Nan'weight=119)
G.add_edge('Pair','Payao'weight=143)
G.add_edge('Lampang','Payao'weight=142)
G.add_edge('Lampang','Chiangrai'weight=229)
G.add_edge('Chiangmai','Chiangrai'weight=190)
G.add_edge('Chiangmai','Maehongsorn'weight=237)
G.add_edge('Payao','Chiangrai'weight=92)
G.add_edge('Payao','Nan'weight=148)